"""empty message

Revision ID: 6c521b9b0a33
Revises: fe9a8f4b2586
Create Date: 2018-11-29 11:19:29.943609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c521b9b0a33'
down_revision = 'fe9a8f4b2586'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'ghost', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'ghost', 'ghost_type', ['type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ghost', type_='foreignkey')
    op.drop_constraint(None, 'ghost', type_='foreignkey')
    # ### end Alembic commands ###
